download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/paloaltonetworks-panos-3.2.0.tar.gz
format_version: 1.0.0
name: panos
namespace: paloaltonetworks
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.2.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/paloaltonetworks/panos/versions/3.2.0/
